kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "meerkat-dsa.fullname" . }}-config
  labels:
    {{- include "meerkat-dsa.labels" . | nindent 4 }}
data:
  {{- if .Values.administrator_email }}
  administrator_email: {{ .Values.administrator_email }}
  {{- end }}
  administrator_email_public: {{ .Values.administrator_email_public | default false | ternary 1 0 | quote }}
  bind_min_sleep_ms: {{ .Values.bind_min_sleep_ms | default 1000 | quote }}
  bind_sleep_range_ms: {{ .Values.bind_sleep_range_ms | default 3000 | quote }}
  bulk_insert_mode: {{ .Values.bulk_insert_mode | ternary 1 0 | quote }}
  {{- if .Values.client_cert_engine }}
  client_cert_engine: {{ .Values.client_cert_engine }}
  {{- end }}
  chaining_tls_optional: {{ .Values.chaining_tls_optional | ternary 1 0 | quote }}
  default_entry_ttl: {{ .Values.default_entry_ttl | default "60" | quote }}
  enable_dop: {{ .Values.enable_dop | ternary 1 0 | quote }}
  enable_dsp: {{ .Values.enable_dsp | ternary 1 0 | quote }}
  {{- if .Values.ecdh_curves }}
  ecdh_curves: {{ .Values.ecdh_curves | quote }}
  {{- end }}
  enable_dap: {{ .Values.enable_dap | ternary 1 0 | quote }}
  entries_per_subordinates_page: {{ .Values.entries_per_subordinates_page | default 100 | quote }}
  forbid_anonymous_bind: {{ .Values.forbid_anonymous_bind | ternary 1 0 | quote }}
  honor_cipher_order: {{ .Values.honor_cipher_order | ternary 1 0 | quote }}
  idm_buffer_size: {{ .Values.idm_buffer_size | default "1000000" | quote }}
  idm_port: {{ .Values.idm_port | default 4632 | quote }}
  idms_port: {{ .Values.idms_port | default 44632 | quote }}
  # init_js: use initJsConfigName
  lcr_parallelism: {{ .Values.lcr_parallelism | default 0 | quote }}
  ldap_buffer_size: {{ .Values.ldap_buffer_size | default "1000000" | quote }}
  ldap_port: {{ .Values.ldap_port | default 389 | quote }}
  ldaps_port: {{ .Values.ldaps_port | default 636 | quote }}
  local_qualifier_points_for_using_ssl3: {{ .Values.local_qualifier_points_for_using_starttls | default 8 | quote }}
  local_qualifier_points_for_using_starttls: {{ .Values.local_qualifier_points_for_using_starttls | default 16 | quote }}
  local_qualifier_points_for_using_tls: {{ .Values.local_qualifier_points_for_using_starttls | default 32 | quote }}
  local_qualifier_points_for_using_tls_1_0: {{ .Values.local_qualifier_points_for_using_starttls | default 16 | quote }}
  local_qualifier_points_for_using_tls_1_1: {{ .Values.local_qualifier_points_for_using_starttls | default 32 | quote }}
  local_qualifier_points_for_using_tls_1_2: {{ .Values.local_qualifier_points_for_using_starttls | default 64 | quote }}
  local_qualifier_points_for_using_tls_1_3: {{ .Values.local_qualifier_points_for_using_starttls | default 128 | quote }}
  {{- if .Values.log_file }}
  log_file: {{ .Values.log_file | quote }}
  log_file_max_size: {{ .Values.log_file_max_size | default 1000000 | quote }}
  log_file_max_files: {{ .Values.log_file_max_files | default 100 | quote }}
  log_zip: {{ .Values.log_zip | ternary 1 0 | quote }}
  log_tailable: {{ .Values.log_tailable | ternary 1 0 | quote }}
  {{- end }}
  {{- if .Values.log_http }}
  log_http: {{ .Values.log_http | ternary 1 0 | quote }}
  {{- end }}
  log_json: {{ .Values.log_json | ternary 1 0 | quote }}
  log_level: {{ .Values.log_level | default "debug" }}
  lookup_uncert_strong_auth: {{ .Values.lookup_uncert_strong_auth | ternary 1 0 | quote }}
  max_concurrent_operations_per_connection: {{ .Values.max_concurrent_operations_per_connection | default 20 | quote }}
  max_connections: {{ .Values.max_connections | default 250 | quote }}
  max_connections_per_address: {{ .Values.max_connections_per_address | default 100 | quote }}
  max_idm_pdu_size: {{ .Values.max_idm_pdu_size | default "1000000" | quote }}
  max_idm_segments: {{ .Values.max_idm_segments | default 10 | quote }}
  max_pre_bind_requests: {{ .Values.max_pre_bind_requests | default 2 | quote }}
  min_auth_level_for_chaining: {{ .Values.min_auth_level_for_chaining | default 1 | quote }}
  min_auth_level_for_ob: {{ .Values.min_auth_level_for_ob | default 1 | quote }}
  min_auth_local_qualifier_for_chaining: {{ .Values.min_auth_local_qualifier_for_chaining | default 0 | quote }}
  min_auth_local_qualifier_for_ob: {{ .Values.min_auth_local_qualifier_for_ob | default 0 | quote }}
  min_transfer_speed_bytes_per_minute: {{ .Values.min_transfer_speed_bytes_per_minute | default 1000 | quote }}
  {{- if .Values.my_access_point_nsaps }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  my_access_point_nsaps: {{ join " " .Values.my_access_point_nsaps }}
  {{- end }}
  no_color: {{ .Values.no_color | ternary 1 0 | quote }}
  no_console: {{ .Values.no_console | ternary 1 0 | quote }}
  no_timestamp: {{ .Values.no_timestamp | ternary 1 0 | quote }}
  ob_auto_accept: {{ .Values.ob_auto_accept | ternary 1 0 | quote }}
  open_top_level: {{ .Values.open_top_level | ternary 1 0 | quote }}
  {{- if .Values.private_key_engine }}
  private_key_engine: {{ .Values.private_key_engine }}
  {{- end }}
  prohibit_chaining: {{ .Values.prohibit_chaining | ternary 1 0 | quote }}
  scr_parallelism: {{ .Values.scr_parallelism | default 0 | quote }}
  {{- if .Values.scvp_attr_cert_checks }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  scvp_attr_cert_checks: {{ join ", " .Values.scvp_attr_cert_checks }}
  {{- end }}
  {{- if .Values.scvp_attr_cert_want_backs }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  scvp_attr_cert_want_backs: {{ join ", " .Values.scvp_attr_cert_want_backs }}
  {{- end }}
  scvp_cached_response: {{ .Values.scvp_cached_response | ternary 1 0 | quote }}
  scvp_disclose_ae_title: {{ .Values.scvp_disclose_ae_title | ternary 1 0 | quote }}
  scvp_full_request_in_response: {{ .Values.scvp_full_request_in_response | ternary 1 0 | quote }}
  {{- if .Values.scvp_hash_algorithm }}
  scvp_hash_algorithm: {{ .Values.scvp_hash_algorithm | quote }}
  {{- end }}
  scvp_inhibit_any_policy: {{ .Values.scvp_inhibit_any_policy | ternary 1 0 | quote }}
  scvp_inhibit_policy_mapping: {{ .Values.scvp_inhibit_policy_mapping | ternary 1 0 | quote }}
  {{- if .Values.scvp_public_key_cert_checks }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  scvp_public_key_cert_checks: {{ join ", " .Values.scvp_public_key_cert_checks }}
  {{- end }}
  {{- if .Values.scvp_public_key_cert_want_backs }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  scvp_public_key_cert_want_backs: {{ join ", " .Values.scvp_public_key_cert_want_backs }}
  {{- end }}
  {{- if .Values.scvp_requestor_text }}
  scvp_requestor_text: {{ .Values.scvp_requestor_text | quote }}
  {{- end }}
  scvp_require_explicit_policy: {{ .Values.scvp_require_explicit_policy | ternary 1 0 | quote }}
  scvp_response_validation_policy_by_ref: {{ .Values.scvp_response_validation_policy_by_ref | ternary 1 0 | quote }}
  {{- if .Values.scvp_signature_algorithm }}
  scvp_signature_algorithm: {{ .Values.scvp_signature_algorithm | quote }}
  {{- end }}
  {{- if .Values.scvp_url }}
  scvp_url: {{ .Values.scvp_url | quote }}
  {{- end }}
  {{- if .Values.scvp_validation_algorithm_id }}
  scvp_validation_algorithm_id: {{ .Values.scvp_validation_algorithm_id | quote }}
  {{- end }}
  {{- if .Values.scvp_validation_policy_ref_id }}
  scvp_validation_policy_ref_id: {{ .Values.scvp_validation_policy_ref_id | quote }}
  {{- end }}
  sentinel_domain: sentinel.meerkat.wildboar.software
  {{- if .Values.signing_acceptable_cert_policies }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  signing_acceptable_cert_policies: {{ join ", " .Values.signing_acceptable_cert_policies }}
  {{- end }}
  {{- if .Values.signing_bind_acceptable_cert_policies }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  signing_bind_acceptable_cert_policies: {{ join ", " .Values.signing_bind_acceptable_cert_policies }}
  {{- end }}
  signing_bind_crl_dp_attempts_per_cert: {{ .Values.signing_bind_crl_dp_attempts_per_cert | default 3 | quote }}
  signing_bind_max_endpoints_per_crl_dp: {{ .Values.signing_bind_max_endpoints_per_crl_dp | default 3 | quote }}
  signing_bind_ocsp_checkiness: {{ .Values.signing_bind_ocsp_checkiness | default -1 | quote }}
  signing_bind_ocsp_max_requests_per_cert: {{ .Values.signing_bind_ocsp_max_requests_per_cert | default 3 | quote }}
  signing_bind_ocsp_sign_requests: {{ .Values.signing_bind_ocsp_sign_requests | ternary 1 0 | quote }}
  signing_bind_ocsp_timeout: {{ .Values.signing_bind_ocsp_timeout | default 5 | quote }}
  signing_bind_ocsp_unknown_is_failure: {{ .Values.signing_bind_ocsp_unknown_is_failure | ternary 1 0 | quote }}
  signing_bind_remote_crl_cache_ttl: {{ .Values.signing_bind_remote_crl_cache_ttl | default 3600 | quote }}
  signing_bind_remote_crl_checkiness: {{ .Values.signing_bind_remote_crl_checkiness | default 0 | quote }}
  signing_bind_remote_crl_size_limit: {{ .Values.signing_bind_remote_crl_size_limit | default "1000000" | quote }}
  {{- if .Values.signing_bind_remote_crl_supported_protocols }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  signing_bind_remote_crl_supported_protocols: {{ join ", " .Values.signing_bind_remote_crl_supported_protocols }}
  {{- end }}
  signing_bind_remote_crl_timeout: {{ .Values.signing_bind_remote_crl_timeout | default 5 | quote }}
  signing_bind_tolerate_unavailable_remote_crl: {{ .Values.signing_bind_tolerate_unavailable_remote_crl | ternary 1 0 | quote }}
  # signing_ca_file: use signingCaConfigName
  # signing_cert_chain: use signingSecretName
  signing_crl_dp_attempts_per_cert: {{ .Values.signing_crl_dp_attempts_per_cert | default 3 | quote }}
  # signing_crl_file: use signingCrlConfigName
  signing_disable_verification: {{ .Values.signing_disable_verification | ternary 1 0 | quote }}
  signing_errors_min_auth_level: {{ .Values.signing_errors_min_auth_level | default 1 | quote }}
  signing_errors_min_auth_local_qualifier: {{ .Values.signing_errors_min_auth_local_qualifier | default 0 | quote }}
  signing_errors_min_auth_signed: {{ .Values.signing_errors_min_auth_signed | ternary 1 0 | quote }}
  # signing_key: signingSecretName
  signing_max_endpoints_per_crl_dp: {{ .Values.signing_errors_min_auth_level | default 3 | quote }}
  signing_min_auth_level: {{ .Values.signing_min_auth_level | default 1 | quote }}
  signing_min_auth_local_qualifier: {{ .Values.signing_min_auth_local_qualifier | default 0 | quote }}
  signing_min_auth_signed: {{ .Values.signing_min_auth_signed | ternary 1 0 | quote }}
  signing_ocsp_checkiness: {{ .Values.signing_ocsp_checkiness | default -1 | quote }}
  signing_ocsp_max_requests_per_cert: {{ .Values.signing_ocsp_max_requests_per_cert | default 3 | quote }}
  signing_ocsp_replay_window: {{ .Values.signing_ocsp_replay_window | default 15 | quote }}
  signing_ocsp_response_size_limit: {{ .Values.signing_ocsp_response_size_limit | default 10000 | quote }}
  signing_ocsp_sign_requests: {{ .Values.signing_min_auth_signed | ternary 1 0 | quote }}
  signing_ocsp_timeout: {{ .Values.signing_ocsp_timeout | default 5 | quote }}
  signing_ocsp_unknown_is_failure: {{ .Values.signing_ocsp_unknown_is_failure | ternary 1 0 | quote }}
  {{- if .Values.signing_permitted_algorithms }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  signing_permitted_algorithms: {{ join ", " .Values.signing_permitted_algorithms }}
  {{- end }}
  signing_remote_crl_cache_ttl: {{ .Values.signing_remote_crl_cache_ttl | default 3600 | quote }}
  signing_remote_crl_checkiness: {{ .Values.signing_remote_crl_checkiness | default 0 | quote }}
  signing_remote_crl_size_limit: {{ .Values.signing_remote_crl_size_limit | default "1000000" | quote }}
  {{- if .Values.signing_remote_crl_supported_protocols }}
  # NOTE: The `join` function is not documented currently.
  # See: https://stackoverflow.com/questions/47668793/helm-generate-comma-separated-list
  signing_remote_crl_supported_protocols: {{ join ", " .Values.signing_remote_crl_supported_protocols }}
  {{- end }}
  signing_remote_crl_timeout: {{ .Values.signing_remote_crl_timeout | default 5 | quote }}
  signing_required_for_chaining: {{ .Values.signing_required_for_chaining | ternary 1 0 | quote }}
  signing_required_for_ob: {{ .Values.signing_required_for_ob | ternary 1 0 | quote }}
  signing_tolerate_unavailable_remote_crl: {{ .Values.signing_tolerate_unavailable_remote_crl | ternary 1 0 | quote }}
  tcp_no_delay: {{ .Values.tcp_no_delay | ternary 1 0 | quote }}
  tcp_timeout_in_seconds: {{ .Values.tcp_timeout_in_seconds | default 60 | quote }}
  tls_answer_ocsp_requests: {{ .Values.tls_answer_ocsp_requests | ternary 1 0 | quote }}
  # tls_ca_file: tlsCaConfigName
  # tls_cert_file: use tlsSecretName
  {{- if .Values.tls_ciphers }}
  tls_ciphers: {{ .Values.tls_ciphers }}
  {{- end }}
  tls_client_cert_auth: {{ .Values.tls_client_cert_auth | ternary 1 0 | quote }}
  # tls_crl_file: use tlsCrlConfigName
  # tls_dh_param_file: use dhParamSecretName
  tls_handshake_timeout_in_seconds: {{ .Values.tls_handshake_timeout_in_seconds | default 10 | quote }}
  # tls_key_file: use tlsSecretName
  # tls_key_passphrase: "himom42"
  {{- if .Values.tls_min_version }}
  tls_min_version: {{ .Values.tls_min_version }}
  {{- end }}
  {{- if .Values.tls_max_version }}
  tls_max_version: {{ .Values.tls_max_version }}
  {{- end }}
  tls_ocsp_checkiness: {{ .Values.tls_ocsp_checkiness | default -1 | quote }}
  tls_ocsp_max_requests_per_cert: {{ .Values.tls_ocsp_max_requests_per_cert | default 3 | quote }}
  tls_ocsp_replay_window: {{ .Values.tls_ocsp_replay_window | default 15 | quote }}
  tls_ocsp_response_size_limit: {{ .Values.tls_ocsp_response_size_limit | default "10000" | quote }}
  tls_ocsp_sign_requests: {{ .Values.tls_ocsp_sign_requests | ternary 1 0 | quote }}
  tls_ocsp_timeout: {{ .Values.tls_ocsp_timeout | default 5 | quote }}
  tls_ocsp_unknown_is_failure: {{ .Values.tls_ocsp_unknown_is_failure | ternary 1 0 | quote }}
  # TODO: tls_pfx_file: not supported by this Helm chart. Use tls_key_file and tls_cert_file instead.
  tls_reject_unauthorized_clients: {{ .Values.tls_reject_unauthorized_clients | ternary 1 0 | quote }}
  tls_reject_unauthorized_servers: {{ .Values.tls_reject_unauthorized_servers | ternary 1 0 | quote }}
  tls_request_ocsp: {{ .Values.tls_request_ocsp | ternary 1 0 | quote }}
  tls_session_timeout_in_seconds: {{ .Values.tls_session_timeout_in_seconds | default 600 | quote }}
  {{- if .Values.tls_sig_algs }}
  tls_sig_algs: {{ .Values.tls_sig_algs | quote }}
  {{- end }}
  transcode_distinguished_values_to_der: {{ .Values.transcode_distinguished_values_to_der | ternary 1 0 | quote }}
  transcode_values_to_der: {{ .Values.transcode_values_to_der | ternary 1 0 | quote }}
  # trust_anchors_file: use signingTrustAnchorListConfigName
  use_database_when_there_are_x_subordinates: {{ .Values.use_database_when_there_are_x_subordinates | default "1000" | quote }}
  {{- if .Values.vendor_name }}
  vendor_name: {{ .Values.vendor_name | quote }}
  {{- end }}
  {{- if .Values.vendor_version }}
  vendor_version: {{ .Values.vendor_version | quote }}
  {{- end }}
  {{- if .Values.web_admin_auth_username }}
  web_admin_auth_username: {{ .Values.web_admin_auth_username | quote }}
  {{- end }}
  {{- if .Values.web_admin_auth_password }}
  web_admin_auth_password: {{ .Values.web_admin_auth_password | quote }}
  {{- end }}
  {{- if .Values.web_admin_auth_realm }}
  web_admin_auth_realm: {{ .Values.web_admin_auth_realm | quote }}
  {{- end }}
  web_admin_use_tls: {{ .Values.web_admin_use_tls | default true | ternary 1 0 | quote }}
  web_admin_port: {{ .Values.web_admin_port | default "18080" | quote }}

  {{- if .Values.init }}
  init: |-
{{ toYaml .Values.init | indent 4 }}
  {{- end }}