{{- if eq (.Values.networkPolicyEnabled | toString) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ include "meerkat-dsa.fullname" . }}-directory-netpol"
spec:
  podSelector:
    matchLabels:
      {{- include "meerkat-dsa.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicyIngressOverride }}
  ingress:
  # Ensure that everything within this chart can still reach everything else.
  - from:
    podSelector:
      matchLabels:
        {{- include "meerkat-dsa.selectorLabels" . | nindent 10 }}
  {{- .Values.networkPolicyIngressOverride | toYaml | nindent 2 }}
  {{- else }}
  ingress:
  - {}
  {{- end }}
  {{- if .Values.networkPolicyEgressOverride }}
  egress:
  {{- .Values.networkPolicyEgressOverride | toYaml | nindent 2 }}
  {{- else }}
  # Allows all egress, which might be necessary for accessing the DBMS, OCSP,
  # remote CRLs, and chaining to other DSAs.
  egress:
  - {}
  {{- end }}
{{- end }}