# You really need a signing cert if you expect chaining to work, because
# Meerkat DSA gets its AE-Title from the cert's subject name, and if multiple
# DSAs have an empty AE-Title, chaining might fail because a loop is more likely
# to be detected.
{{- if not .Values.signingSecretName }}
{{ $cn := uuidv4 }}
{{ $dnsname := print $cn ".local" }}
{{ $keypair := genSelfSignedCert $cn nil (list $dnsname) 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "meerkat-dsa.fullname" . }}-signing"
  annotations:
    wildboar.software/exists-because: "You didn't define a signingSecretName in your Helm chart for Meerkat DSA to use."
    wildboar.software/used-by: "Meerkat DSA"
type: kubernetes.io/tls
data:
  tls.crt: {{ $keypair.Cert | b64enc }}
  tls.key: {{ $keypair.Key | b64enc }}
{{- end }}
