replicaCount: 1
image:
  repository: wildboarsoftware/meerkat-dsa
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
idm:
  port: 4632
idms:
  port: 44632
ldap:
  port: 389
ldaps:
  port: 636
admin:
  type: ClusterIP
  port: 18080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
dapEnabled: true
ldapEnabled: true
webAdminEnabled: true
locale: en_US.utf8
# signingSecretName: meerkat-dsa-signing
# tlsSecretName: meerkat-dsa-tls
sentinelDomain: sentinel.meerkat.wildboar.software
databaseSecretName: meerkat-dsa-database
# administratorEmail: example@example.com
bindMinSleep: 1000
bindSleepRange: 3000
minAuthLevelForOB: 1
minAuthLocalQualifierForOB: 128
# myAccessPointNSAPs: idm://example.com:4632 idms://example.com:44632
useDatabaseWhenThereAreXSubordinates: 1000
entriesPerSubordinatesPage: 100
transcodeValuestoDER: true
transcodeDistinguishedValuesToDER: true
bulkInsertMode: false
# init
