image:
  repository: ghcr.io/wildboar-software/meerkat-dsa
  pullPolicy: Always # TODO: Change this to IfNotPresent after Beta is over.
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  # A value of "local" for `externalTrafficPolicy` will maintain the client's IP
  # address in Azure and other cloud providers.
  externalTrafficPolicy: Local
adminService:
  type: ClusterIP
  # A value of "local" for `externalTrafficPolicy` will maintain the client's IP
  # address in Azure and other cloud providers.
  externalTrafficPolicy: Local
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
resetDatabase: false
dangerouslyExposeWebAdmin: false
networkPolicyEnabled: false
networkPolicyIngressOverride:
  - from:
    - podSelector:
        matchLabels:
          app: whatever
    ports:
    - port: 1234
      protocol: TCP
networkPolicyEgressOverride:
  - to:
    - ipBlock:
        cidr: x.x.x.x/32
    ports:
    - port: 1234
      protocol: TCP
# Necessary for configuring:
# 1. Pod affinity to put your Meerkat DSA instance near your DBMS, and
# 2. Network policy, permitting Meerkat DSA to connect to your DBMS.
# databaseLabelSelector:
#   matchLabels:
#     app: mysql

# This should be a secret of type "tls".
# See: https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
# This may be the same secret as `tlsSecretName`.
# signingSecretName: meerkat-signing-secret

# This should be a secret of type "tls".
# See: https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
# This may be the same secret as `signingSecretName`.
# tlsSecretName: meerkat-tls-secret

# Mandatory: an opaque secret containing a field called `databaseUrl` which
# contains the database URL as used by a Prisma client.
# See: https://www.prisma.io/docs/reference/database-reference/connection-urls
# A secret is needed for this because the URL typically has a username and
# password in it.
databaseSecretName: meerkat-database-secret

# This MUST contain the following keys:
# - `ca.pem`: The certificate authority bundle as a concatenation of PEM-encoded X.509 certificates.
# tlsCaConfigName: meerkat-ca-config

# This MUST contain the following keys:
# - `crl.pem`: All certificate revocation lists as a concatenation of PEM-encoded CRLs.
# tlsCrlConfigName: meerkat-crl-config

# This MUST contain the following keys:
# - `dhparam.pem`: The PEM-encoded Diffie-Hellman Parameters
# dhParamSecretName: meerkat-dhparam-secret

# This MUST contain the following keys:
# - `ca.pem`: The certificate authority bundle as a concatenation of PEM-encoded X.509 certificates.
# signingCaConfigName: meerkat-ca-config

# This MUST contain the following keys:
# - `tal.cmsc`: The IETF RFC 5914 Trust Anchor List as a binary CMS message (not DER-encoded)
# signingTrustAnchorListConfigName: meerkat-tal-config

# This MUST contain the following keys:
# - `crl.pem`: All certificate revocation lists as a concatenation of PEM-encoded CRLs.
# signingCrlConfigName: meerkat-crl-config

# This MUST contain the following keys:
# - `acert.pem`: The attribute certification path, as described in:
# https://wildboar-software.github.io/directory/docs/env#meerkatattrcertchainfile
# attributeCertificationPathConfigName: meerkat-attcert-config

# This MUST contain the following keys:
# - `init`: The init script to run at startup to customize your Meerkat DSA instance.
# initJsConfigName: meerkat-init-js

# This should be a secret of type "tls".
# See: https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret
# A secret is needed for this because the URL typically has a username and
# password in it.
# webAdminProxySecretName: web-admin-proxy-secret

# administrator_email: jonathan@wilbur.space
# administrator_email_public: true
bind_min_sleep_ms: 1000
bind_sleep_range_ms: 3000
bulk_insert_mode: false
# client_cert_engine: pkcs11
chaining_check_sig: true
chaining_sign_requests: true
chaining_tls_optional: false
default_entry_ttl: 60
# ecdh_curves: P-521:P-384:P-256
enable_dap: true
enable_dop: false
enable_dsp: false
entries_per_subordinates_page: 100
forbid_anonymous_bind: false
honor_cipher_order: true
idm_buffer_size: "1000000"
idm_port: 4632
idms_port: 44632
# init_js: use initJsConfigName
itot_port: 1102
itots_port: 11102
itot_abort_timeout_in_seconds: 3
# itot_max_nsdu_size: "65531"
# itot_max_tpdu_size: "65500"
# itot_max_tsdu_size: "10000000"
# itot_max_ssdu_size: "10000000"
itot_max_presentation_contexts: 10
# itot_acse_password: banana
disable_itot_chaining: false
lcr_parallelism: 0
ldap_buffer_size: "1000000"
ldap_port: 389
ldaps_port: 636
local_qualifier_points_for_using_ssl3: 8
local_qualifier_points_for_using_starttls: 8
local_qualifier_points_for_using_tls: 32
local_qualifier_points_for_using_tls_1_0: 32
local_qualifier_points_for_using_tls_1_1: 64
local_qualifier_points_for_using_tls_1_2: 128
local_qualifier_points_for_using_tls_1_3: 256
log_bound_dn: false
# log_file: /var/log/meerkat.log
# log_file_max_files: 100
# log_file_max_size: "1000000"
log_http: false
log_json: false
log_level: info
log_tailable: false
log_zip: true
lookup_uncert_strong_auth: false
max_concurrent_operations_per_connection: 100
max_connections: 250
max_connections_per_address: 100
max_idm_pdu_size: "1000000"
max_idm_segments: 10
max_pre_bind_requests: 0
min_auth_level_for_chaining: 1
min_auth_level_for_ob: 1
min_auth_local_qualifier_for_chaining: 0
min_auth_local_qualifier_for_ob: 0
min_transfer_speed_bytes_per_minute: 1000
# my_access_point_nsaps:
#   - "itot://example.com:1707"
no_color: false
no_console: false
no_timestamp: false
ob_auto_accept: false
open_top_level: false
# private_key_engine: pkcs11
prohibit_chaining: false
reveal_user_pwd: false
src_parallelism: 0
# scvp_attr_cert_checks:
#   - "2.5.4.3"
# scvp_attr_cert_want_backs:
#   - "2.5.4.3"
scvp_cached_response: false
scvp_disclose_ae_title: false
scvp_full_request_in_response: false
# scvp_hash_algorithm: "2.5.4.3"
scvp_inhibit_any_policy: false
scvp_inhibit_policy_mapping: false
# scvp_public_key_cert_checks:
#   - "2.5.4.3"
# scvp_public_key_cert_want_backs:
#   - "2.5.4.3"
# scvp_requestor_text: "Hi Mom"
scvp_require_explicit_policy: false
scvp_response_validation_policy_by_ref: false
# scvp_signature_algorithm: "2.5.4.3"
# scvp_url: https://example.com/scvp
# scvp_validation_algorithm_id: "2.5.4.3"
# scvp_validation_policy_ref_id: "2.5.4.3"
sentinel_domain: sentinel.meerkat.wildboar.software
# signing_acceptable_cert_policies:
#   - "2.5.4.3"
# signing_bind_acceptable_cert_policies:
#   - "2.5.4.3"
signing_bind_crl_dp_attempts_per_cert: 3
signing_bind_max_endpoints_per_crl_dp: 3
signing_bind_ocsp_checkiness: -1
signing_bind_ocsp_max_requests_per_cert: 3
signing_bind_ocsp_sign_requests: false
signing_bind_ocsp_timeout: 5
signing_bind_ocsp_unknown_is_failure: true
signing_bind_remote_crl_cache_ttl: 3600
signing_bind_remote_crl_checkiness: 0
signing_bind_remote_crl_size_limit: "1000000"
signing_bind_remote_crl_supported_protocols:
  - "http"
  - "https"
  - "ftp"
  - "ftps"
  - "ldap"
  - "ldaps"
  - "http2"
signing_bind_remote_crl_timeout: 5
signing_bind_tolerate_unavailable_remote_crl: true
# signing_ca_file: use signingCaConfigName
# signing_cert_chain: use signingSecretName
signing_crl_dp_attempts_per_cert: 3
# signing_crl_file: use signingCrlConfigName
signing_disable_verification: false
signing_errors_min_auth_level: 1
signing_errors_min_auth_local_qualifier: 0
signing_errors_min_auth_signed: true
# signing_key: signingSecretName
signing_max_endpoints_per_crl_dp: 3
signing_min_auth_level: 1
signing_min_auth_local_qualifier: 0
signing_min_auth_signed: true
signing_ocsp_checkiness: -1
signing_ocsp_max_requests_per_cert: 3
signing_ocsp_replay_window: 15
signing_ocsp_response_size_limit: 10000
signing_ocsp_sign_requests: false
signing_ocsp_timeout: 5
signing_ocsp_unknown_is_failure: true
# signing_permitted_algorithms:
#   - "2.5.4.3"
signing_remote_crl_cache_ttl: 3600
signing_remote_crl_checkiness: 0
signing_remote_crl_size_limit: "1000000"
signing_remote_crl_supported_protocols:
  - "http"
  - "https"
  - "ftp"
  - "ftps"
  - "ldap"
  - "ldaps"
  - "http2"
signing_remote_crl_timeout: 5
signing_required_for_chaining: true
signing_required_for_ob: true
signing_tolerate_unavailable_remote_crl: true
tcp_no_delay: false
tcp_timeout_in_seconds: 60
tls_answer_ocsp_requests: false
# tls_ca_file: tlsCaConfigName
# tls_cert_file: use tlsSecretName
# tls_ciphers: RSA-PSK-AES256-GCM-SHA384:!RC4
tls_client_cert_auth: false
# tls_crl_file: use tlsCrlConfigName
# tls_dh_param_file: use dhParamSecretName
tls_handshake_timeout_in_seconds: 10
# tls_key_file: use tlsSecretName
# TODO: tls_key_passphrase: not supported by this Helm chart.
tls_max_version: "TLSv1.3"
tls_min_version: "TLSv1.2"
tls_ocsp_checkiness: -1
tls_ocsp_max_requests_per_cert: 3
tls_ocsp_replay_window: 15
tls_ocsp_response_size_limit: 10000
tls_ocsp_sign_requests: false
tls_ocsp_timeout: 5
tls_ocsp_unknown_is_failure: true
# TODO: tls_pfx_file: not supported by this Helm chart. Use tls_key_file and tls_cert_file instead.
tls_reject_unauthorized_clients: false
tls_reject_unauthorized_servers: true
tls_request_ocsp: false
# tls_session_timeout_in_seconds: 300
# tls_sig_algs: rsa_pss_pss_sha512
transcode_distinguished_values_to_der: true
transcode_values_to_der: true
# trust_anchors_file: signingTrustAnchorListConfigName
use_database_when_there_are_x_subordinates: 1000
# vendor_name: ""
# vendor_version: ""
# web_admin_auth_username: admin
# web_admin_auth_password: "USJ6TrD3GLOAsHN7F7GgkEq/VsQe33wwaPuMm3Ormf8="
# web_admin_auth_realm: "Bigboi's Playhouse"
web_admin_use_tls: true
web_admin_port: 18080