CREATE DATABASE directory1;
CREATE DATABASE directory2;
CREATE DATABASE directory3;
CREATE USER 'user1' IDENTIFIED BY 'asdf1';
CREATE USER 'user2' IDENTIFIED BY 'asdf2';
CREATE USER 'user3' IDENTIFIED BY 'asdf3';
GRANT ALL PRIVILEGES ON directory1.* TO 'user1';
GRANT ALL PRIVILEGES ON directory2.* TO 'user2';
GRANT ALL PRIVILEGES ON directory3.* TO 'user3';
