#!/bin/sh
set -e

mkdir -p /var/lib/meerkat /var/log/meerkat /usr/lib/meerkat

if ! id meerkat >/dev/null 2>&1; then
    adduser --system --group --home /var/lib/meerkat meerkat
fi

# I don't know why I have to do this here. Normally, I don't need execute
# permissions to run a program with `npx`.
chmod +x /usr/lib/meerkat/node_modules/prisma/build/index.js

chown -R meerkat:meerkat /var/lib/meerkat /var/log/meerkat

systemctl daemon-reload
systemctl unmask meerkat || true
systemctl enable meerkat || true

exit 0
