#!/bin/sh
set -e

case "$1" in
  purge)
    # destructive cleanup
    rm -rf /var/log/meerkat || true
    rm -rf /var/lib/meerkat || true
    rm -rf /etc/meerkat || true
    ;;
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
    # usually nothing
    ;;
esac

exit 0
