// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
    tutorialSidebar: [
        'docs',
        {
            type: 'category',
            label: 'X.500',
            items: [
                'intro',
                'why-not-ldap',
                'uses',
            ],
        },
        {
            type: 'category',
            label: 'Meerkat DSA',
            items: [
                'setup',
                'env',
                'webadmin',
                'database',
                'authorization',
                'authentication',
                'logging-monitoring',
                'schema',
                'networking',
                'tls',
                'online-pki',
                'signing',
                'opbinding',
                'dynamic',
                'administration',
                'troubleshooting',
                'advice',
                'usage',
                'zonal',
                'telemetry',
                'conformance',
                'deviations-nuances',
                'information-disclosure',
                'architecture',
                'roadmap',
            ],
        },
        {
            type: 'category',
            label: 'Clients',
            items: [
                'x500cli',
                'studio',
            ],
        },
        {
            type: 'category',
            label: 'Tutorials',
            items: [
                'tutorial01',
                'tutorial02',
            ],
        },
        {
            type: 'category',
            label: 'Reference',
            items: [
                'asn1',
                'specs',
                'client-config',
            ],
        },
        {
            type: 'category',
            label: 'Change Logs',
            items: [
                'changelog-meerkat',
            ],
        },
        {
            type: 'category',
            label: 'For Developers',
            items: [
                'versioning',
            ],
        },
        {
            type: 'doc',
            id: 'support',
            label: 'Support / Help',
        },
    ],
};

module.exports = sidebars;
