name: meerkat-dsa
base: core20
version: '1.0.0-beta.21'
summary: X.500 Directory (DSA) and LDAP Server
description: |
  Fully-featured X.500 directory server / directory system agent (DSA)
  and Lightweight Directory Access Protocol (LDAP) server written in
  TypeScript by Wildboar Software.
license: MIT
grade: devel
confinement: strict
parts:
  dsa:
    plugin: npm
    source: dist/apps/meerkat
    npm-node-version: 17.3.0
    override-build: |
      # 17.3.0 is unavailable using build-packages.
      curl -s https://nodejs.org/dist/v17.3.0/node-v17.3.0-linux-x64.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      # Necessary to install, because NPM runs as "nobody," but snaps install as root.
      # See: https://forum.snapcraft.io/t/issue-with-nodejs-plugin-when-using-base-keyword/11109/8
      npm config set unsafe-perm true
      npm install --no-save --no-audit --no-fund --production
      # I think this is already covered by npm install, but just to be sure...
      npx prisma generate
      chmod +x ./start-meerkat
      cp -r * $SNAPCRAFT_PART_INSTALL
apps:
  meerkat-dsa:
    command: ./start-meerkat
    daemon: simple
    refresh-mode: restart # Will be changed to "endure" eventually.
    restart-condition: never # Booting up is resource intensive. You wouldn't want it to loop.
    plugs:
      - network-observe
