/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function oidFromStr(s: string): Array<number> | null
export function oidFromBytes(b: Uint8Array): Array<number> | null
