#!/bin/sh
cd /usr/lib/meerkat

# If the migration fails, still carry on: we do not want a failed migration
# (which is infrequently needed to begin with) to make us unable to start
# Meerkat DSA
#
# NOTE: Prisma seems to search for migrations relative to the config file, not
# the current directory.
PRISMA_HIDE_UPDATE_MESSAGE=1 /usr/bin/npx prisma migrate deploy \
    --schema /usr/lib/meerkat/prisma/schema.prisma \
    --config /usr/lib/meerkat/prisma.config.ts || true

exec /usr/bin/node /usr/lib/meerkat/main.js start "$@"
